language: node_js
node_js:
  - 0.4
  - 0.5
  - 0.6
  - 0.7
  - 0.8
script: "tap test/"
services: mysql
before_script:
  - mysql < dev/createDB.sql
notifications:
  email: dev@totendev.com
  irc:
    channels:
      - "irc.freenode.org#TotenDev"
