language: node_js
node_js:
  - 0.6
  - 0.8
  - 0.10
  - 0.11
script: "tap test/"
services: mysql
before_script:
  - mysql < dev/createDB.sql
notifications:
  email: dev@totendev.com
  irc:
    channels:
      - "irc.freenode.org#TotenDev"
