SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `apnrs`.`apnrs_devices` CHANGE COLUMN `lastRegisterDate` `lastRegisterDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP  ;

ALTER TABLE `apnrs`.`apnrs_tags` CHANGE COLUMN `createDate` `createDate` TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP'  ;

ALTER TABLE `apnrs`.`apnrs_devices_register` CHANGE COLUMN `createDate` `createDate` TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP'  ;

CREATE  TABLE IF NOT EXISTS `apnrs`.`apnrs_messages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `msg_alert` TEXT NULL DEFAULT NULL ,
  `msg_sound` VARCHAR(45) NULL DEFAULT NULL ,
  `msg_badge` INT(11) NULL DEFAULT NULL ,
  `isBroadcasting` TINYINT(1) NOT NULL ,
  `tags` TEXT NULL DEFAULT NULL ,
  `sentDate` TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP' ,
  `deviceToken` VARCHAR(64) NOT NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
